"""add_detailed_minutes_to_summary

Revision ID: 48940594b2d1
Revises: 23160bf014ef
Create Date: 2025-12-05 18:05:36.875986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48940594b2d1'
down_revision: Union[str, None] = '23160bf014ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER TABLE for constraints, so we only add the column
    # The foreign key constraints should already exist from previous migrations
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detailed_minutes', sa.Text(), nullable=True, comment='Detailed structured meeting minutes in markdown format'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('summaries', schema=None) as batch_op:
        batch_op.drop_column('detailed_minutes')
    # ### end Alembic commands ###

